### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by smashkins** [Acidham/chromium-hist-bookmarks#1]
I use Brave browser but it doesn't work. I use bh command but the debug error says:

```
[16:53:15.572] Logging Started...
[16:53:21.312] Chromium&Firefox Bookmarks and History[Script Filter] Queuing argument ''
[16:53:21.408] Chromium&Firefox Bookmarks and History[Script Filter] Script with argv '' finished
[16:53:21.411] ERROR: Chromium&Firefox Bookmarks and History[Script Filter] Code 1: /Users/<user>/Library/Application Support/Chromium/Default/History NOT found
/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser/Default/History found
/Users/<user>/Library/Application Support/BraveSoftware/Brave-Browser-Dev/Default/History NOT found
/Users/<user>/Library/Application Support/Google/Chrome/Default/History found
/Users/<user>/Library/Application Support/Vivaldi/Default/History NOT found
/Users/<user>/Library/Application Support/com.operasoftware.Opera/History NOT found
Traceback (most recent call last):
  File "/Users/<user>a/SynologyDrive/Drive/Alfred workflow/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.123E23AF-7740-48F4-838D-B4B916A7695A/chrom_history.py", line 164, in <module>
    fire_locked_db = path_to_fire_history()
  File "/Users/<user>a/SynologyDrive/Drive/Alfred workflow/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.123E23AF-7740-48F4-838D-B4B916A7695A/chrom_history.py", line 85, in path_to_fire_history
    f_home_dirs = ['{0}/{1}'.format(f_home, o) for o in os.listdir(f_home)]
OSError: [Errno 2] No such file or directory: '/Users/<user>/Library/Application Support/Firefox/Profiles'
```

**Comment by Acidham** [comment]
Can you please check the Firefox profile directory is available on your file system, assuming you hab Firefox installed.

If not, please figure out where Firefox store profile
