### ISSUE TITLE
BUG：History function can't run successfully

### ISSUE THREAD

**Issue by MartinYuan1995** [Acidham/chromium-hist-bookmarks#36]
Hey buddy, when I try to type bh, nothing happens. The debugger running records as follows:
[17:17:57.836] Chromium Bookmarks and History Search[Script Filter] Queuing argument ''
[17:17:58.234] Chromium Bookmarks and History Search[Script Filter] Script with argv '' finished
[17:17:58.240] ERROR: Chromium Bookmarks and History Search[Script Filter] Code 1: Cache Dir: /Users/letlifebebeautiful/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.apple.alfred.workflow.chromium-hist
Data Dir: /Users/letlifebebeautiful/Library/Application Support/Alfred/Workflow Data/com.apple.alfred.workflow.chromium-hist
PYTHON VERSION: 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)]
/Users/letlifebebeautiful/Library/Application Support/Google/Chrome/Default/History → found

                    SELECT DISTINCT urls.url, urls.title, urls.visit_count, (urls.last_visit_time/1000000 + (strftime('%s', '1601-01-01')))
                    FROM urls, visits
                    WHERE urls.id = visits.url AND
                    urls.title IS NOT NULL AND
                    urls.title != '' order by last_visit_time DESC; 
Traceback (most recent call last):
  File "chrom_history.py", line 343, in <module>
    main()
  File "chrom_history.py", line 316, in main
    if favicon:
UnboundLocalError: local variable 'favicon' referenced before assignment

**Comment by Acidham** [comment]
Uupsss nasty bug. Thx for reporting! Should be fixed with: https://github.com/Acidham/chromium-hist-bookmarks/releases/tag/v4.1.4

**Comment by MartinYuan1995** [comment]
wow! thank you, you solve problems with such remarkable speed.

**Comment by Acidham** [comment]
A well described bug report with all necessary information leads to quick bug fixes 😉
